server:
  error:
    path: /error-custom

spring:
  # 데이터베이스 접속정보 설정
  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/profile
    driver-class-name: org.mariadb.jdbc.Driver
  # 타임리프 설정 (기존에 JSP를 사용하던 방식을 .html 방식으로 사용설정)
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  # 파일첨부 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      location: /spring-boot-fileupload-temp
  #security:
    #user:
      #name: test
      #password: test1234@@
# mybatis 설정
mybatis:
  mapper-locations:
  - classpath:config/mapper/Board.xml
  - classpath:config/mapper/Member.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level: 
    root: info
    '[kr.songjava]': DEBUG
    
# 파일 업로드 관련 설정    
file:
  root-path: /spring-boot-fileupload    
